const $=id=>document.getElementById(id);
const copy={es:{live:"AL AIRE",idle:"EN ESPERA",connect:"Conectar",cut:"Cortar",src:"Fuentes",twH:"Canal sin #. Chat real, sin contrasena.",ttH:"1) Crea clave gratis en eulerstream.com  2) Pegala abajo  3) Tu LIVE de TikTok debe estar abierto  4) Conectar.",twPh:"canal, sin #",ttPh:"usuario, sin @",demo:"Ensayo",demoH:"Simulado. Apagalo cuando conectes en vivo.",voice:"Voz",ttsOn:"Leer en voz alta",name:"Decir el nombre",test:"Probar voz",pause:"Pausa",resume:"Seguir",skip:"Saltar",waiting:"En silencio",reading:"Leyendo",queue:"en cola",speak:"Voxlive listo. Ya puedes oir el chat.",stage:"Escenario",studio:"Estudio",rate:"Velocidad",voiceL:"Voz",twOk:"Escuchando Twitch",twBad:"No se pudo abrir Twitch.",ttWeb:"TikTok en vivo",ttNeed:"Falta la clave de TikTok.",ttBad:"No se pudo abrir TikTok. Revisa clave y que el LIVE este abierto."},en:{live:"ON AIR",idle:"IDLE",connect:"Connect",cut:"Cut",src:"Sources",twH:"Channel, no #.",ttH:"Free key at eulerstream.com. Paste it. Be live. Connect.",twPh:"channel, no #",ttPh:"username, no @",demo:"Rehearsal",demoH:"Simulated. Turn off when live.",voice:"Voice",ttsOn:"Read aloud",name:"Say the name",test:"Test voice",pause:"Pause",resume:"Resume",skip:"Skip",waiting:"Silent",reading:"Reading",queue:"queued",speak:"Voxlive is ready.",stage:"Stage",studio:"Studio",rate:"Rate",voiceL:"Voice",twOk:"Listening to Twitch",twBad:"Twitch failed.",ttWeb:"TikTok live",ttNeed:"TikTok API key required.",ttBad:"TikTok failed. Check key and that LIVE is on."}};
let lang="es",ttsOn=true,readName=true,paused=false,rate=1,twitchOn=false,tiktokOn=false,demoOn=true;
let twitchSock=null,tiktokSock=null,demoTimer=null,selectedVoice="",speaking=null,msgN=0,unlocked=false,speakStarted=0;
const queue=[],feed=$("feed");
const demoScript=[{platform:"tiktok",kind:"chat",user:"valeria.r",display:"valeria.r",text:"hola, acabo de entrar"},{platform:"twitch",kind:"chat",user:"nexo_",display:"nexo_",text:"vamos con todo hoy"},{platform:"tiktok",kind:"gift",user:"mar.ok",display:"mar.ok",text:"envio Rosa",giftName:"Rosa",giftCount:5},{platform:"twitch",kind:"chat",user:"SofiaPlays",display:"SofiaPlays",text:"ese clip estuvo brutal"}];
const t=()=>copy[lang];
function applyLang(){const c=t();$("h-src").textContent=c.src;$("h-voice").textContent=c.voice;$("twitch-h").textContent=c.twH;$("tiktok-h").textContent=c.ttH;$("demo-l").textContent=c.demo;$("demo-h").textContent=c.demoH;$("tts-l").textContent=c.ttsOn;$("name-l").textContent=c.name;$("test").textContent=c.test;$("skip").textContent=c.skip;$("pause").textContent=paused?c.resume:c.pause;$("twitch").placeholder=c.twPh;$("tiktok").placeholder=c.ttPh;$("twitch-btn").textContent=twitchOn?c.cut:c.connect;$("tiktok-btn").textContent=tiktokOn?c.cut:c.connect;$("now-k").textContent=speaking?c.reading:c.waiting;$("stage").textContent=document.body.classList.contains("stage")?c.studio:c.stage;$("rate-l").textContent=c.rate;$("voice-l").textContent=c.voiceL;$("livepill").textContent=(twitchOn||tiktokOn||demoOn)?c.live:c.idle;$("livepill").className="pill"+(twitchOn||tiktokOn||demoOn?"":" off");}
function escapeHtml(s){return String(s).replace(/&/g,"&").replace(/</g,"<").replace(/>/g,">");}
function initials(name){return String(name||"?").trim().slice(0,2).toUpperCase();}
function clock(ts){const d=new Date(ts||Date.now());return String(d.getHours()).padStart(2,"0")+":"+String(d.getMinutes()).padStart(2,"0");}
function setDot(id,state){$(id).className="dot"+(state==="live"?" live":state==="error"?" err":state==="connecting"?" wait":"");}
function addMsg(m){msgN++;const wrap=document.createElement("article");wrap.className="msg"+(m.kind!=="chat"?" event":"");wrap.innerHTML='<div class="av">'+escapeHtml(initials(m.displayName||m.user))+'</div><div><div class="name">'+escapeHtml(m.displayName||m.user)+(m.source==="demo"?'<span class="tag">Ensayo</span>':'')+'</div><div class="body">'+escapeHtml(m.text||'')+'</div></div><div><div class="time">'+clock(m.ts)+'</div><div class="plat">'+escapeHtml(m.platform||'')+'</div></div>';feed.appendChild(wrap);feed.scrollTop=feed.scrollHeight;while(feed.children.length>220)feed.removeChild(feed.firstChild);$("msgcount").textContent=msgN+" mensajes";if(ttsOn&&unlocked){if(queue.length>10)queue.shift();queue.push(m);$("q").textContent=queue.length+" "+t().queue;kick();}}
function speechText(m){const name=readName?(m.displayName||m.user):"";if(m.kind==="gift")return (name?name+" ":"")+"envio "+(m.giftName||"un regalo");if(m.kind==="follow")return (name||"alguien")+" empezo a seguir";if(m.kind==="sub")return (name||"alguien")+" se suscribio";if(m.kind==="bits")return (name||"alguien")+" mando bits";return name?name+" dice "+(m.text||""):(m.text||"");}
function pickVoice(){const voices=speechSynthesis.getVoices()||[];if(selectedVoice){const exact=voices.find(v=>v.name===selectedVoice);if(exact)return exact;}return voices.find(v=>(v.lang||"").toLowerCase().indexOf(lang)===0)||voices[0]||null;}
function fillVoices(){const sel=$("voice");const voices=speechSynthesis.getVoices()||[];const prev=selectedVoice||sel.value;sel.innerHTML="";voices.forEach(v=>{const o=document.createElement("option");o.value=v.name;o.textContent=v.name+" ("+v.lang+")";sel.appendChild(o);});if(prev)sel.value=prev;selectedVoice=sel.value;}
function kick(){if(!unlocked||paused||speaking||!ttsOn)return;const next=queue.shift();$("q").textContent=queue.length+" "+t().queue;if(!next){speaking=null;$("now-k").textContent=t().waiting;$("now-text").textContent="-";$("now-user").textContent="";return;}speaking=next;speakStarted=Date.now();$("now-k").textContent=t().reading;$("now-text").textContent=next.text||"";$("now-user").textContent=(next.displayName||next.user||"")+(next.platform?" - "+next.platform:"");const u=new SpeechSynthesisUtterance(speechText(next));u.lang=lang==="es"?"es-ES":"en-US";u.rate=rate;const pref=pickVoice();if(pref){u.voice=pref;u.lang=pref.lang||u.lang;}u.onend=function(){speaking=null;kick();};u.onerror=function(){speaking=null;setTimeout(kick,120);};try{speechSynthesis.resume();speechSynthesis.speak(u);}catch(e){speaking=null;}}
function startDemo(){if(demoTimer)clearInterval(demoTimer);demoOn=true;$("demo").checked=true;let i=0;const tick=function(){const item=demoScript[i%demoScript.length];i++;addMsg({platform:item.platform,kind:item.kind,user:item.user,displayName:item.display,text:item.text,giftName:item.giftName,giftCount:item.giftCount,bits:item.bits,ts:Date.now(),source:"demo"});};tick();demoTimer=setInterval(tick,3200);applyLang();}
function stopDemo(){demoOn=false;$("demo").checked=false;if(demoTimer)clearInterval(demoTimer);demoTimer=null;applyLang();}
function parseTwitch(raw){let tags={},rest=raw;if(rest.charAt(0)==="@"){const sp=rest.indexOf(" ");rest.slice(1,sp).split(";").forEach(p=>{const parts=p.split("=");tags[parts[0]]=parts[1]||"";});rest=rest.slice(sp+1);}const prefixEnd=rest.charAt(0)===":"?rest.indexOf(" "):-1;const prefix=prefixEnd>0?rest.slice(1,prefixEnd):"";const after=prefixEnd>0?rest.slice(prefixEnd+1):rest;const cmdEnd=after.indexOf(" :");const head=cmdEnd>=0?after.slice(0,cmdEnd):after;const text=cmdEnd>=0?after.slice(cmdEnd+2):"";return {tags:tags,nick:prefix.split("!")[0],cmd:head.split(" ")[0],text:text};}
function startTwitch(channel){stopTwitch();channel=channel.replace(/^#/,"").trim().toLowerCase();if(channel.length<3)return;unlocked=true;twitchOn=true;setDot("twitch-dot","connecting");$("twitch-st").textContent="...";applyLang();const nick="justinfan"+Math.floor(10000+Math.random()*80000);const ws=new WebSocket("wss://irc-ws.chat.twitch.tv:443");twitchSock=ws;ws.onopen=function(){ws.send("CAP REQ :twitch.tv/tags twitch.tv/commands");ws.send("PASS SCHMOOPIIE");ws.send("NICK "+nick);ws.send("JOIN #"+channel);};ws.onmessage=function(ev){String(ev.data).split("\r\n").forEach(function(line){if(!line)return;if(line.indexOf("PING")===0){ws.send("PONG :tmi.twitch.tv");return;}const m=parseTwitch(line);if(m.cmd==="001"||m.cmd==="JOIN"){twitchOn=true;setDot("twitch-dot","live");$("twitch-st").textContent=t().twOk;applyLang();}if(m.cmd==="PRIVMSG")addMsg({platform:"twitch",kind:"chat",user:m.nick,displayName:m.tags["display-name"]||m.nick,text:m.text,ts:Date.now(),source:"live"});});};ws.onerror=function(){setDot("twitch-dot","error");$("twitch-st").textContent=t().twBad;twitchOn=false;applyLang();};ws.onclose=function(){if(twitchSock===ws){twitchOn=false;setDot("twitch-dot","");applyLang();}};}
function stopTwitch(){if(twitchSock){try{twitchSock.close();}catch(e){}twitchSock=null;}twitchOn=false;setDot("twitch-dot","");$("twitch-st").textContent="-";}
function ingestTikTok(obj){if(!obj)return;const ev=(obj.event||obj.type||obj.method||"").toLowerCase();
const data=obj.data||obj.payload||obj;
const user=data.user||data.userInfo||{};
const name=user.nickname||user.uniqueId||user.nickName||data.uniqueId||data.nickname||"tiktok";
const uname=user.uniqueId||user.nickName||name;
if(ev.indexOf("chat")>=0||ev.indexOf("comment")>=0||data.comment){addMsg({platform:"tiktok",kind:"chat",user:uname,displayName:name,text:data.comment||data.text||data.content||"",ts:Date.now(),source:"live"});return;}
if(ev.indexOf("gift")>=0){const g=data.giftName||(data.gift&&data.gift.name)||"regalo";addMsg({platform:"tiktok",kind:"gift",user:uname,displayName:name,text:"envio "+g,giftName:g,giftCount:data.repeatCount||1,ts:Date.now(),source:"live"});return;}
if(ev.indexOf("follow")>=0||ev.indexOf("social")>=0){addMsg({platform:"tiktok",kind:"follow",user:uname,displayName:name,text:"empezo a seguir",ts:Date.now(),source:"live"});return;}
if(Array.isArray(obj.messages))obj.messages.forEach(ingestTikTok);}
function startTikTok(user){stopTikTok();user=user.replace(/^@/,"").trim();const key=($("ttkey").value||"").trim();if(user.length<2)return;if(!key){setDot("tiktok-dot","error");$("tiktok-st").textContent=t().ttNeed;return;}unlocked=true;stopDemo();tiktokOn=true;setDot("tiktok-dot","connecting");$("tiktok-st").textContent="...";applyLang();
const urls=["wss://ws.eulerstream.com?uniqueId="+encodeURIComponent(user)+"&apiKey="+encodeURIComponent(key),"wss://api.tik.tools/?uniqueId="+encodeURIComponent(user)+"&apiKey="+encodeURIComponent(key)];
let i=0;function tryNext(){if(i>=urls.length){tiktokOn=false;setDot("tiktok-dot","error");$("tiktok-st").textContent=t().ttBad;applyLang();return;}const url=urls[i++];let opened=false;const ws=new WebSocket(url);tiktokSock=ws;ws.onopen=function(){opened=true;tiktokOn=true;setDot("tiktok-dot","live");$("tiktok-st").textContent=t().ttWeb;applyLang();};ws.onmessage=function(ev){let raw=ev.data;if(typeof raw!=="string")return;try{const obj=JSON.parse(raw);if(obj.event==="error"||obj.type==="error"){setDot("tiktok-dot","error");$("tiktok-st").textContent=obj.message||t().ttBad;return;}ingestTikTok(obj);}catch(e){}};ws.onerror=function(){};ws.onclose=function(){if(tiktokSock===ws){if(!opened)tryNext();else{tiktokOn=false;setDot("tiktok-dot","");applyLang();}}};}
tryNext();}
function stopTikTok(){if(tiktokSock){try{tiktokSock.close();}catch(e){}tiktokSock=null;}tiktokOn=false;setDot("tiktok-dot","");$("tiktok-st").textContent="-";}
function save(){localStorage.setItem("voxlive",JSON.stringify({lang:lang,twitch:$("twitch").value,tiktok:$("tiktok").value,ttkey:$("ttkey").value,ttsOn:ttsOn,readName:readName,rate:rate,selectedVoice:selectedVoice}));}
function load(){try{const s=JSON.parse(localStorage.getItem("voxlive")||"{}");if(s.lang)lang=s.lang;if(s.twitch)$("twitch").value=s.twitch;if(s.tiktok)$("tiktok").value=s.tiktok;if(s.ttkey)$("ttkey").value=s.ttkey;if(typeof s.ttsOn==="boolean"){ttsOn=s.ttsOn;$("tts").checked=ttsOn;}if(typeof s.readName==="boolean"){readName=s.readName;$("readname").checked=readName;}if(s.rate){rate=Number(s.rate);$("rate").value=rate;$("rate-v").textContent=rate.toFixed(1)+"x";}if(s.selectedVoice)selectedVoice=s.selectedVoice;$("es").classList.toggle("on",lang==="es");$("en").classList.toggle("on",lang==="en");}catch(e){}}
$("es").onclick=function(){lang="es";$("es").classList.add("on");$("en").classList.remove("on");applyLang();save();};
$("en").onclick=function(){lang="en";$("en").classList.add("on");$("es").classList.remove("on");applyLang();save();};
$("tts").onchange=function(e){ttsOn=e.target.checked;if(!ttsOn){try{speechSynthesis.cancel();}catch(err){}queue.length=0;speaking=null;}save();};
$("readname").onchange=function(e){readName=e.target.checked;save();};
$("voice").onchange=function(e){selectedVoice=e.target.value;save();};
$("rate").oninput=function(e){rate=Number(e.target.value);$("rate-v").textContent=rate.toFixed(1)+"x";save();};
$("demo").onchange=function(e){if(e.target.checked)startDemo();else stopDemo();};
$("test").onclick=function(){unlocked=true;try{speechSynthesis.cancel();}catch(e){}speaking=null;queue.length=0;const u=new SpeechSynthesisUtterance(t().speak);u.lang="es-ES";u.rate=rate;const pref=pickVoice();if(pref)u.voice=pref;u.onend=function(){kick();};speechSynthesis.speak(u);};
$("skip").onclick=function(){try{speechSynthesis.cancel();}catch(e){}speaking=null;kick();};
$("pause").onclick=function(){paused=!paused;$("pause").textContent=paused?t().resume:t().pause;if(paused)try{speechSynthesis.pause();}catch(e){}else{try{speechSynthesis.resume();}catch(e){}if(!speaking)kick();}};
$("stage").onclick=function(){document.body.classList.toggle("stage");applyLang();};
$("twitch-btn").onclick=function(){if(twitchOn)stopTwitch();else{stopDemo();startTwitch($("twitch").value);}applyLang();save();};
$("tiktok-btn").onclick=function(){if(tiktokOn)stopTikTok();else startTikTok($("tiktok").value);applyLang();save();};
$("twitch").onchange=save;$("tiktok").onchange=save;$("ttkey").onchange=save;
setInterval(function(){if(speaking&&speakStarted&&Date.now()-speakStarted>8000){try{speechSynthesis.cancel();}catch(e){}speaking=null;kick();}},1000);
speechSynthesis.onvoiceschanged=fillVoices;load();fillVoices();applyLang();startDemo();
